import "./theme.css";
import "@coinbase/onchainkit/styles.css";
import type { Metadata, Viewport } from "next";
import "./globals.css";
import { Providers } from "./providers";
// import { Shantell_Sans } from 'next/font/google';
import localFont from "next/font/local";
import Footer from "@/components/Footer";


// export const delius = Shantell_Sans({
//   subsets: ['latin'],
//   weight: ['300', '400', '500', '600', '700', '800',], // add the required weight property
//   variable: '--font-shantell-sans',
//   display: 'swap',
// });

const hatton = localFont({
  src: [
    {
      path: "../lib/fonts/PP-Hatton-Ultralight-200.otf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../lib/fonts/PP-Hatton-Medium-500.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../lib/fonts/PP-Hatton-Bold-700.otf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-hatton",
});

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export async function generateMetadata(): Promise<Metadata> {
  const URL = process.env.NEXT_PUBLIC_URL;
  return {
    title: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
    description:
      "Generated by `create-onchain --mini`, a Next.js template for MiniKit",
    other: {
      "fc:frame": JSON.stringify({
        version: "next",
        imageUrl: process.env.NEXT_PUBLIC_APP_HERO_IMAGE,
        button: {
          title: `Launch ${process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME}`,
          action: {
            type: "launch_frame",
            name: process.env.NEXT_PUBLIC_ONCHAINKIT_PROJECT_NAME,
            url: URL,
            splashImageUrl: process.env.NEXT_PUBLIC_SPLASH_IMAGE,
            splashBackgroundColor:
              process.env.NEXT_PUBLIC_SPLASH_BACKGROUND_COLOR,
          },
        },
      }),
    },
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-background ${hatton.className} font-[400]`}>
        <Providers>
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
